Add function to create replacement map based on input wire expressions.
uwsampl/lakeroad pull request #384
Opened 2023-11-05 17:20 UTC by thiskappaisgrey

Added a function that pattern matches an expression against:
```
(Var "i_name" 1)
```
and create a replacement map:
```
[ (( Var "i_name" 1), i_name) ]
```

2023-11-05 18:35 UTC, gussmith23 requested changes

2023-11-05 18:35 UTC, gussmith23 commented on lakeroad-egglog/tests/egglog_tests.rs
> +    /// You can pass the replacement map returned by this function to replace_in_expr
Could you add a [doctest](https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html) to this?

e.g.
```suggestion
    /// Given an expression, like `(Var "i_out" 1)` - create a replacement map that replaces that with `i_out`
    /// You can pass the replacement map returned by this function to replace_in_expr
    /// ```
    /// <some code that shows what this function does, with assert statements to check the output>
    /// ```
```

2023-11-05 18:36 UTC, gussmith23 commented
Thank you @thiskappaisgrey ! Just requested a bit more documentation.

2023-11-06 04:37 UTC, thiskappaisgrey commented
Added documentation. It doesn't run but you can add it to an example test maybe..? @gussmith23

2023-11-06 23:01 UTC, gussmith23 approved these changes
Thanks @thiskappaisgrey !

2023-11-06 23:02 UTC, merged

2023-11-06 23:02 UTC, gussmith23 commented
Sorry, I didn't realize the function wasn't at the top level, so of course doctests didn't work. My misunderstanding!