Vcanumalla/import dsp48e1
uwsampl/lakeroad pull request #427
Opened 2024-02-29 23:34 UTC by vcanumalla

2024-04-03 04:09 UTC, gussmith23 requested changes
Needs tests! Please add tests first.

2024-04-03 20:05 UTC, gussmith23 commented
Removing myself from review until you add tests

2024-04-03 20:05 UTC, gussmith23 commented
Also please make the title of this PR less auto-generated

2024-05-13 22:57 UTC, vcanumalla commented
Added a bunch of tests: mostly 1 stage tests, a couple of 2 stage tests, and a variety of bitwidths. Most higher bitwidths timeout, so I kept most pretty small so I could actually get synthesized stuff.

2024-05-14 00:37 UTC, gussmith23 requested changes
please get ci passing first!

2024-05-14 16:18 UTC, gussmith23 requested changes
This is looking good! A few small comments.

2024-05-14 16:18 UTC, gussmith23 commented on integration_tests/lakeroad/xilinx-virtex/virtex_muladd_1_stage_unsigned_14_bit.sv
> +//  if [ -z ${LAKEROAD_PRIVATE_DIR+x} ]; then \
If this test works, then the simulator stuff shouldn't be commented out

2024-05-14 16:18 UTC, gussmith23 commented on integration_tests/lakeroad/xilinx-virtex/virtex_muladd_1_stage_unsigned_9_bit.sv
> +//  if [ -z ${LAKEROAD_PRIVATE_DIR+x} ]; then \
similar with this test

2024-05-14 16:18 UTC, gussmith23 commented on integration_tests/lakeroad/xilinx-virtex/virtex_mulsub_1_stage_unsigned_14_bit.sv
> +//  if [ -z ${LAKEROAD_PRIVATE_DIR+x} ]; then \
similar with this test

2024-05-14 16:18 UTC, gussmith23 commented on integration_tests/lakeroad/xilinx-virtex/virtex_mulsub_1_stage_unsigned_9_bit.sv
> +//  if [ -z ${LAKEROAD_PRIVATE_DIR+x} ]; then \
and this one -- please fix the rest of the tests as well

2024-05-14 16:20 UTC, vcanumalla commented on integration_tests/lakeroad/xilinx-virtex/virtex_mulsub_1_stage_unsigned_9_bit.sv
> +//  if [ -z ${LAKEROAD_PRIVATE_DIR+x} ]; then \
oh thats my bad. I thought that it was running it as one line, not as a comment. Will fix, and will re-draft PR if tests fail

2024-05-28 08:08 UTC, vcanumalla commented on racket/test-lattice-ecp5-alu54a.rkt
>              (bv #b0000 4)))
```suggestion
            (bv #b0000 4)))
            
```

2024-05-28 08:08 UTC, vcanumalla commented on racket/test-lattice-ecp5-alu54a.rkt
>    (define-symbolic opcode (bitvector 11))
```suggestion
  (define-symbolic opcode (bitvector 11))
  
```

2024-05-28 08:08 UTC, vcanumalla commented on racket/test-lattice-ecp5-alu54a.rkt
>  (test-case "get an input on the second cycle and return it on the third"
```suggestion
(test-case "get an input on the second cycle and return it on the third"

```

2024-05-28 08:08 UTC, vcanumalla commented on racket/test-lattice-ecp5-alu54a.rkt
>              (bv #b0000 4)))
```suggestion
            (bv #b0000 4)))
            
```

2024-05-28 08:09 UTC, vcanumalla commented on racket/test-lattice-ecp5-alu54a.rkt
>  (test-case "get an input on the second cycle and return it on the third"
```suggestion
(test-case "get an input on the second cycle and return it on the third"

```

2024-05-28 08:09 UTC, vcanumalla commented on racket/test-lattice-ecp5-alu54a.rkt
>    (define-symbolic opcode (bitvector 11))
```suggestion
  (define-symbolic opcode (bitvector 11))
  
```

2024-05-28 08:10 UTC, vcanumalla commented on run-tests.sh
> +
```suggestion
```

2024-07-03 20:08 UTC, gussmith23 approved these changes
once CI passes, good to go!

2024-07-03 20:12 UTC, gussmith23 commented
seems like i'm suddenly running into some unrelated CI/actions issues, related to this issue:
https://github.com/actions/checkout/issues/1590

2024-07-03 20:25 UTC, gussmith23 commented
See https://github.com/docker/login-action/issues/745

2024-07-05 23:39 UTC, merged